---
title: "Data Pre-processing"
author: "Ryan Ghan"
date: "October 27, 2014"
output: html_document
---

This section uses data from the `AppliedPredictiveModeling` package and functions from the `caret`, `corrplot`, `dplyr` and `lattice` packages.

## Getting started
Load the necessary libraries and data set into **R**:
```{r load.package.data, message=FALSE}
library(AppliedPredictiveModeling)
library(dplyr)
## Load the 
data(segmentationOriginal)
segmentationOriginal <- tbl_df(segmentationOriginal)
```
Make some adjustments to the data.
```{r}
## Retain only the 'training' set
segTrain <- filter(segmentationOriginal, Case == "Train")
## Remove the first three columns (identifier columns)
segTrainX <- select(segTrain, -(1:3))
segTrainClass <- segTrain$Class
```
___
### *Transformations*

___
### *Filtering*

___
### *Creating Dummy Variables*

```{r, message=FALSE}
library(caret)  # relocate this at some point
data(cars)
type <- c("convertible", "coupe", "hatchback", "sedan", "wagon")
cars$Type <- factor(apply(cars[, 14:18], 1, function(x) type[which(x == 1)]))
carSubset <- cars[sample(1:nrow(cars), 20), c(1, 2, 19)]
```

```{r}
head(carSubset)
levels(carSubset$Type)
```

```{r}
simpleMod <- dummyVars(~Mileage + Type,
                       data = carSubset,
                       ## Remove the variable name from the
                       ## column name
                       levelsOnly = TRUE)
simpleMod

withInteraction <- dummyVars(~Mileage + Type + Mileage:Type,
                             data = carSubset,
                             levelsOnly = TRUE)
withInteraction
predict(withInteraction, head(carSubset))
```


___
### *Exercises*

___
### R and package versions used
```{r}
sessionInfo()
```